### ISSUE TITLE
Organization icon

### ISSUE THREAD

**Issue by olegbrz** [PABUMA/RyuQ#10]
@ajnebro and I were talking about the need to create a logo for the organization.

Feel free to use this issue to publish **ideas**, **concepts**, or your **own designs**. I propose to vote after some time and choose the design that we all like the most.

One of the important requirements is that the design should not have elements taken from other authors to avoid copyright conflicts.

**Comment by olegbrz** [comment]
Taking advantage of my free time and inspiration today, I created this "minimalistic design", which represents the graphic visualizations of multiple sequence alignments.

<p align="center">
  <img src="https://user-images.githubusercontent.com/43888615/118301279-2bc77580-b4e3-11eb-8817-178aa156877b.png" width="800">
</p>

---

<p>
<img src="https://user-images.githubusercontent.com/43888615/118359602-8cf35580-b584-11eb-8b53-58ed9323b034.png" width="800">
</p>

---

<p align="center">
  <img src="https://user-images.githubusercontent.com/43888615/118294734-51508100-b4db-11eb-9007-dace7937f34a.png" width="300">
</p>

**Comment by MiguelPadillaR** [comment]
Como dato, Ryu en japonés también significa dragón:
![image](https://user-images.githubusercontent.com/80248429/118776012-cd561a80-b887-11eb-8074-cb41750bccdd.png)
