### ISSUE TITLE
Missing Maven dependencies

### ISSUE THREAD

**Issue by olegbrz** [PABUMA/RyuQ#11]
The jMetal dependencies specified in the [`pom.xml`](https://github.com/PABUMA/RyuQ/blob/main/pom.xml#L35-L45) file cannot be found with Maven.

![image](https://user-images.githubusercontent.com/43888615/118362182-b74a1080-b58e-11eb-8666-09c8006d4304.png)

**Comment by olegbrz** [comment]
The last version available at [mvnreporistory](https://mvnrepository.com/artifact/org.uma.jmetal/jmetal-core) is `5.10`.

**Comment by ajnebro** [comment]
Snapshot versions of GitHub projects are not included in [Central Repository](https://search.maven.org/) nor [Mvn Repository](https://mvnrepository.com/). To use them, the `pom.xml` file has to be modified as indicated here: https://dzone.com/articles/how-to-use-snapshot-of-library-in-maven-project

**Comment by olegbrz** [comment]
Solved! Thanks!
