### ISSUE TITLE
Develop a first prototype of the variable neighborhood search (VNS) algorithm

### ISSUE THREAD

**Issue by ajnebro** [PABUMA/RyuQ#5]
The first step in the development of a VNS algorithm to solve MSA problems is to start with a version able of dealing with simple binary (e.g., OneMax) problems.

## TO-DO

- [x] Initialize algorithm class
  - [x] `VNS()`
     - [x] `shake()`
     - [x] `generateNeighbourhoods()`
     - [x] `generateInitialSolution()`
     - [x] `stoppingCondition`
     - [x] `fitness()`
- [x] Write examples
- [x] Initialize tests class
  - [x] Define tests

**Comment by olegbrz** [comment]
## Trajectory-based metaheuristics

A trajectory-based metaheuristic iteratively improves a single solution and forms a search trajectory in the solution space. Examples of trajectory-based metaheuristics include Simulated Annealing (SA), Tabu Search (TS), Iterated Local Search (ILS) and Guided Local Search (GLS)

*Source*: [A new cooperative framework for parallel trajectory-based metaheuristics](https://www.sciencedirect.com/science/article/abs/pii/S1568494618300280#:~:text=A%20trajectory%2Dbased%20metaheuristic%20iteratively,(GLS)%20%5B3%5D.)

## Introduction to VNS

Variable neighborhood search (VNS) is a recent metaheuristic for solving combinatorial and global optimization problems whose basic idea is systematic change of neighborhood
within a local search. In this survey paper we present basic rules of VNS and some of its extensions. Moreover, applications are briefly summarized. They comprise heuristic solution of a
variety of optimization problems, ways to accelerate exact algorithms and to analyze heuristic
solution processes, as well as computer-assisted discovery of conjectures in graph theory.

*Source*: [VARIABLE NEIGHBORHOOD SEARCH](https://sci2s.ugr.es/sites/default/files/files/Teaching/GraduatesCourses/Metaheuristicas/Bibliography/VNS.pdf) *Pierre Hansen, Nenad Mladenović*

<p align="center">
<img src="https://user-images.githubusercontent.com/43888615/118358101-95945d80-b57d-11eb-9e16-697cd1d8e930.png", width=300>
</p>

## Pseudocode

```python
def VNS():
    define_neighbourhood_strutures N_k (k=1,...,k_max)
    generateInitialSolution s ∈ S
    while (!stoppingCondition):
        k = 1
        while (k <= k_max):
            s' = shake(s), s' ∈ N_k(s)
            if (fitness(s'') < fitness(s)):
                s = s''
                k = 1
            else:
                k = k + 1
```
![Diagrama de flujo VNS](https://user-images.githubusercontent.com/43888615/118771038-536f6280-b882-11eb-9e91-e505f82be8db.png)

## TO-DO

- [ ] `VNS()`
  - [ ] `shake()`
  - [x] `generateInitialSolution()`
  - [x] `stoppingCondition`
  - [x] `fitness()`
