### ISSUE TITLE
Add .gitignore

### ISSUE THREAD

**Issue by olegbrz** [PABUMA/RyuQ#9]
IDEs generate their project configuration files as IntelliJ's `.idea`.

I suggest adding the [following  `.gitignore`](https://www.toptal.com/developers/gitignore/api/intellij,java,maven) prepared for Eclipse, IntelliJ, Java and Maven to avoid problems with git and keep the repository clean.

**Comment by ajnebro** [comment]
Good idea. Feel free to add it to the project.

**Comment by olegbrz** [comment]
I don't have write permission on this repository, therefore, it won't let me push to any branch. It also won't let me modify the project "trello", nor modify the labels of the issues.

Should I make a fork in my account and then a Pull Request?

**Comment by ajnebro** [comment]
You don't haver write permission? Let me check that.

**Comment by olegbrz** [comment]
![image](https://user-images.githubusercontent.com/43888615/118250989-54ca1500-b4a7-11eb-8f2f-2b505629808d.png)

**Comment by ajnebro** [comment]
Try now, please
